version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "OnlyGodknow"
      MYSQL_ROOT_PASSWORD: "OnlyGodknow"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
